version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.0
  aws-eks: circleci/aws-eks@0.2.6

workflows:
  build-and-push:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          create-repo: true
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
      - aws-eks/update-container-image:
          cluster-name: "${EKS_CLUSTER_NAME}"
          aws-region: "${AWS_DEFAULT_REGION}"
          container-image-updates: '${EKS_CONTAINER_NAME}=${AWS_ACCOUNT_URL}/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}'
          resource-name: "${EKS_DEPLOYMENT_NAME}"
          requires:
            - aws-ecr/build-and-push-image
